export default [
  {
    id: '1',
    src: '1.jpg',
    title: 'Airport',
    author: 'Primero',
    keywords: ['airport, plane', 'trip'],
  },
  {
    id: '2',
    src: '2.jpg',
    title: 'Alone in the lake',
    author: 'Segundo',
    keywords: ['mountains', 'lake', 'landscape'],
  },
  {
    id: '3',
    src: '3.jpg',
    title: 'Calm mountains',
    author: 'tercero',
    keywords: ['boat', 'mountains', 'lake'],
  },
  {
    id: '4',
    src: '4.jpg',
    title: 'Volkswagen',
    author: 'cuarto',
    keywords: ['volkswagen', 'road', 'lake'],
  },
  {
    id: '5',
    src: '5.jpg',
    title: 'Girl',
    author: 'quinto',
    keywords: ['sea', 'ocean', 'girl', 'pool'],
  },
  {
    id: '6',
    src: '6.jpg',
    keywords: ['boat', 'mountains', 'lake', 'windows'],
  },
  {
    id: '7',
    src: '7.jpg',
    title: 'Septimo',
    keywords: ['map', 'world'],
  },
  {
    id: '8',
    src: '8.jpg',
    title: 'Octavo',
    keywords: ['coast', 'city', 'ocean'],
  },
  {
    id: '9',
    src: '9.jpg',
    title: 'noveno',
    keywords: ['sky', 'night', 'camp', 'stars'],
  },
  {
    id: '10',
    src: '10.jpg',
    title: 'decimo',
    keywords: ['viena', 'city', 'canals'],
  },
  {
    id: '11',
    src: '11.jpg',
    title: 'once',
    keywords: ['map', 'roadtrip', 'sunset'],
  },
  {
    id: '12',
    src: '12.jpg',
    title: 'doce',
    keywords: ['greece', 'city', 'stairs'],
  },
  {
    id: '13',
    src: '13.jpg',
    title: 'trece',
    keywords: ['plane', 'clouds', 'flight'],
  },
  {
    id: '14',
    src: '14.jpg',
    title: 'catorce',
    keywords: ['mountains', 'road', 'roadtrip'],
  },
  {
    id: '15',
    src: '15.jpg',
    title: 'quince',
    keywords: ['trip', 'suitcase'],
  },
  {
    id: '16',
    src: '16.jpg',
    title: 'dieciseis',
    keywords: ['volkswagen', 'girl', 'ocean', 'suitcase'],
  },
  {
    id: '17',
    src: '17.jpg',
    title: 'diecisiete',
    keywords: ['girl', 'pool', 'summer'],
  },
  {
    id: '18',
    src: '18.jpg',
    title: 'ejej',
    author: 'dieciocho',
    keywords: ['train', 'landscape'],
  },
  {
    id: '19',
    src: '19.jpg',
    title: 'ejej',
    author: 'diecinueve',
    keywords: ['mountains', 'girl', 'lake'],
  },
  {
    id: '20',
    src: '20.jpg',
    title: 'ohoh',
    keywords: ['city'],
  },
  {
    id: '21',
    src: '21.jpg',
    title: 'ejej',
    author: 'veintiuno',
    keywords: ['flight', 'airport'],
  },
  {
    id: '22',
    src: '22.jpg',
    title: 'lala',
    author: 'veintidos',
    keywords: ['ocean', 'hotel'],
  },
  {
    id: '23',
    src: '23.jpg',
    title: 'lala',
    author: 'veintitres',
    keywords: ['plane', 'mountains', 'flight'],
  },
]
